### ISSUE TITLE
Vapoursynth R58 and Python 3.10 compatibilty

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-rife#13]
trying to install vs-rife in Vapoursynth R58 I get:
```
I:\Hybrid\64bit\Vapoursynth>python -m pip install --upgrade vsrife
Collecting vsrife
  Using cached vsrife-2.0.0-py3-none-any.whl (32.5 MB)
Requirement already satisfied: torch>=1.9.0 in i:\hybrid\64bit\vapoursynth\lib\site-packages (from vsrife) (1.11.0+cu113)
Requirement already satisfied: numpy in i:\hybrid\64bit\vapoursynth\lib\site-packages (from vsrife) (1.22.3)
Collecting VapourSynth>=55
  Using cached VapourSynth-57.zip (567 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Selur\AppData\Local\Temp\pip-install-s7976394\vapoursynth_701a37362cd045f58da4818d07217c99\setup.py", line 64, in <module>
          dll_path = query(winreg.HKEY_LOCAL_MACHINE, REGISTRY_PATH, REGISTRY_KEY)
        File "C:\Users\Selur\AppData\Local\Temp\pip-install-s7976394\vapoursynth_701a37362cd045f58da4818d07217c99\setup.py", line 38, in query
          reg_key = winreg.OpenKey(hkey, path, 0, winreg.KEY_READ)
      FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Selur\AppData\Local\Temp\pip-install-s7976394\vapoursynth_701a37362cd045f58da4818d07217c99\setup.py", line 67, in <module>
          raise OSError("Couldn't detect vapoursynth installation path")
      OSError: Couldn't detect vapoursynth installation path
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

any idea how to fix it?

**Comment by HolyWu** [comment]
> Collecting VapourSynth>=55
>   Using cached VapourSynth-57.zip (567 kB)

Wait until https://pypi.org/project/VapourSynth/#files get updated to R58 for cp310. Or use the installer version rather than the portable version.

**Comment by Selur** [comment]
thanks
