### ISSUE TITLE
Problems with dependencies,...

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-rife#65]
Just wanted to report that using the given commands, fails for me:
```
F:\Hybrid\64bit\Vapoursynth>python -m pip install -U packaging setuptools wheel
Requirement already satisfied: packaging in f:\hybrid\64bit\vapoursynth\lib\site-packages (24.1)
Requirement already satisfied: setuptools in f:\hybrid\64bit\vapoursynth\lib\site-packages (70.0.0)
Collecting setuptools
  Using cached setuptools-75.2.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: wheel in f:\hybrid\64bit\vapoursynth\lib\site-packages (0.44.0)
Using cached setuptools-75.2.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 70.0.0
    Uninstalling setuptools-70.0.0:
      Successfully uninstalled setuptools-70.0.0
Successfully installed setuptools-75.1.0

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

F:\Hybrid\64bit\Vapoursynth>python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in f:\hybrid\64bit\vapoursynth\lib\site-packages (24.2)
Collecting pip
  Using cached pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
Using cached pip-24.3.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.2
    Uninstalling pip-24.2:
      Successfully uninstalled pip-24.2
  WARNING: The scripts pip.exe, pip3.12.exe and pip3.exe are installed in 'F:\Hybrid\64bit\Vapoursynth\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-24.3.1

F:\Hybrid\64bit\Vapoursynth>python -m pip install --pre -U torch torchvision torch_tensorrt --index-url https://download
.pytorch.org/whl/nightly/cu124 --extra-index-url https://pypi.nvidia.com
Looking in indexes: https://download.pytorch.org/whl/nightly/cu124, https://pypi.nvidia.com
Requirement already satisfied: torch in f:\hybrid\64bit\vapoursynth\lib\site-packages (2.6.0.dev20240925+cu124)
Collecting torch
  Using cached https://download.pytorch.org/whl/nightly/cu124/torch-2.6.0.dev20241028%2Bcu124-cp312-cp312-win_amd64.whl (2513.6 MB)
Requirement already satisfied: torchvision in f:\hybrid\64bit\vapoursynth\lib\site-packages (0.20.0.dev20240926+cu124)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/nightly/cu124/torchvision-0.20.0.dev20241028%2Bcu124-cp312-cp312-win_amd64.whl (6.3 MB)
Requirement already satisfied: torch_tensorrt in f:\hybrid\64bit\vapoursynth\lib\site-packages (2.6.0.dev20240926+cu124)
Collecting torch_tensorrt
  Using cached https://download.pytorch.org/whl/nightly/cu124/torch_tensorrt-2.6.0.dev20241028%2Bcu124-cp312-cp312-win_amd64.whl (2.9 MB)
Requirement already satisfied: filelock in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch) (2024.6.1)
Requirement already satisfied: setuptools in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch) (75.1.0)
Requirement already satisfied: sympy==1.13.1 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torchvision) (1.26.4)
Collecting torch
  Using cached https://download.pytorch.org/whl/nightly/cu124/torch-2.6.0.dev20241027%2Bcu124-cp312-cp312-win_amd64.whl (2513.6 MB)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torchvision) (10.1.0)
Requirement already satisfied: tensorrt-cu12==10.3.0 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch_tensorrt) (10.3.0)
Requirement already satisfied: tensorrt-cu12-bindings==10.3.0 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch_tensorrt) (10.3.0)
Requirement already satisfied: tensorrt-cu12-libs==10.3.0 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch_tensorrt) (10.3.0)
Requirement already satisfied: packaging>=23 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch_tensorrt) (24.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from tensorrt-cu12-libs==10.3.0->torch_tensorrt) (12.6.68)
Requirement already satisfied: MarkupSafe>=2.0 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from jinja2->torch) (2.1.5)
Installing collected packages: torch, torchvision, torch_tensorrt
  Attempting uninstall: torch
    Found existing installation: torch 2.6.0.dev20240925+cu124
    Uninstalling torch-2.6.0.dev20240925+cu124:
      Successfully uninstalled torch-2.6.0.dev20240925+cu124
  WARNING: The scripts convert-caffe2-to-onnx.exe, convert-onnx-to-caffe2.exe, torchfrtrace.exe and torchrun.exe are installed in 'F:\Hybrid\64bit\Vapoursynth\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.20.0.dev20240926+cu124
    Uninstalling torchvision-0.20.0.dev20240926+cu124:
      Successfully uninstalled torchvision-0.20.0.dev20240926+cu124
  Attempting uninstall: torch_tensorrt
    Found existing installation: torch_tensorrt 2.6.0.dev20240926+cu124
    Uninstalling torch_tensorrt-2.6.0.dev20240926+cu124:
      Successfully uninstalled torch_tensorrt-2.6.0.dev20240926+cu124
Successfully installed torch-2.6.0.dev20241027+cu124 torch_tensorrt-2.6.0.dev20241028+cu124 torchvision-0.20.0.dev20241028+cu124

F:\Hybrid\64bit\Vapoursynth>python -m pip install -U tensorrt-cu12 tensorrt-cu12_bindings tensorrt-cu12_libs --extra-index-url https://pypi.nvidia.com
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Requirement already satisfied: tensorrt-cu12 in f:\hybrid\64bit\vapoursynth\lib\site-packages (10.3.0)
Collecting tensorrt-cu12
  Using cached tensorrt_cu12-10.5.0-py2.py3-none-any.whl
Requirement already satisfied: tensorrt-cu12_bindings in f:\hybrid\64bit\vapoursynth\lib\site-packages (10.3.0)
Collecting tensorrt-cu12_bindings
  Using cached https://pypi.nvidia.com/tensorrt-cu12-bindings/tensorrt_cu12_bindings-10.5.0-cp312-none-win_amd64.whl (772 kB)
Requirement already satisfied: tensorrt-cu12_libs in f:\hybrid\64bit\vapoursynth\lib\site-packages (10.3.0)
Collecting tensorrt-cu12_libs
  Using cached https://pypi.nvidia.com/tensorrt-cu12-libs/tensorrt_cu12_libs-10.5.0-py2.py3-none-win_amd64.whl (1079.4 MB)
Requirement already satisfied: nvidia-cuda-runtime-cu12 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from tensorrt-cu12_libs) (12.6.68)
Installing collected packages: tensorrt-cu12_bindings, tensorrt-cu12_libs, tensorrt-cu12
  Attempting uninstall: tensorrt-cu12_bindings
    Found existing installation: tensorrt-cu12_bindings 10.3.0
    Uninstalling tensorrt-cu12_bindings-10.3.0:
      Successfully uninstalled tensorrt-cu12_bindings-10.3.0
  Attempting uninstall: tensorrt-cu12_libs
    Found existing installation: tensorrt-cu12_libs 10.3.0
    Uninstalling tensorrt-cu12_libs-10.3.0:
      Successfully uninstalled tensorrt-cu12_libs-10.3.0
  Attempting uninstall: tensorrt-cu12
    Found existing installation: tensorrt-cu12 10.3.0
    Uninstalling tensorrt-cu12-10.3.0:
      Successfully uninstalled tensorrt-cu12-10.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch-tensorrt 2.6.0.dev20241028+cu124 requires tensorrt-cu12==10.3.0, but you have tensorrt-cu12 10.5.0 which is incompatible.
torch-tensorrt 2.6.0.dev20241028+cu124 requires tensorrt-cu12-bindings==10.3.0, but you have tensorrt-cu12-bindings 10.5.0 which is incompatible.
torch-tensorrt 2.6.0.dev20241028+cu124 requires tensorrt-cu12-libs==10.3.0, but you have tensorrt-cu12-libs 10.5.0 which is incompatible.
Successfully installed tensorrt-cu12-10.5.0 tensorrt-cu12_bindings-10.5.0 tensorrt-cu12_libs-10.5.0
```
I'm on Windows 11, with a portable Python and Vapoursynth R70, in case it matters.

**Comment by HolyWu** [comment]
> Successfully installed setuptools-75.1.0
> Successfully installed torch-2.6.0.dev20241027+cu124 torch_tensorrt-2.6.0.dev20241028+cu124 torchvision-0.20.0.dev20241028+cu124
> Successfully installed tensorrt-cu12-10.5.0 tensorrt-cu12_bindings-10.5.0 tensorrt-cu12_libs-10.5.0

THERE IS NO FAILURE! The dependency conflicts message is not uncommon in pip world if you upgrade a package to a version which is outside another package's dependency requirement. It's no harm if it doesn't throw errors when you actually use it.

> Side question: Would it be much trouble to stick to stable releases for the dependencies?

Torch-TensorRT 2.5.0 doesn't have a necessary functionality I need to use, hence 2.6.0.dev is mandatory.

**Comment by Selur** [comment]
Hmm, trying again, with the new instructions, now it crashes:
```
F:\Hybrid\64bit\Vapoursynth>python -m pip install -U packaging setuptools wheel
Requirement already satisfied: packaging in f:\hybrid\64bit\vapoursynth\lib\site-packages (24.1)
Requirement already satisfied: setuptools in f:\hybrid\64bit\vapoursynth\lib\site-packages (70.0.0)
Collecting setuptools
  Downloading setuptools-75.3.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: wheel in f:\hybrid\64bit\vapoursynth\lib\site-packages (0.44.0)
Downloading setuptools-75.3.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 5.3 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 70.0.0
    Uninstalling setuptools-70.0.0:
      Successfully uninstalled setuptools-70.0.0
Successfully installed setuptools-75.1.0

F:\Hybrid\64bit\Vapoursynth>python -m pip install --pre -U torch torchvision --index-url https://download.pytorch.org/whl/nightly/cu124
Looking in indexes: https://download.pytorch.org/whl/nightly/cu124
Requirement already satisfied: torch in f:\hybrid\64bit\vapoursynth\lib\site-packages (2.6.0.dev20240925+cu124)
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/cu124/torch-2.6.0.dev20241031%2Bcu124-cp312-cp312-win_amd64.whl (2513.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 GB 7.3 MB/s eta 0:00:00
Requirement already satisfied: torchvision in f:\hybrid\64bit\vapoursynth\lib\site-packages (0.20.0.dev20240926+cu124)
Collecting torchvision
  Downloading https://download.pytorch.org/whl/nightly/cu124/torchvision-0.20.0.dev20241031%2Bcu124-cp312-cp312-win_amd64.whl (6.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 7.8 MB/s eta 0:00:00
Requirement already satisfied: filelock in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch) (2024.6.1)
Requirement already satisfied: setuptools in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch) (75.1.0)
Requirement already satisfied: sympy==1.13.1 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torchvision) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from torchvision) (10.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from jinja2->torch) (2.1.5)
Installing collected packages: torch, torchvision
  Attempting uninstall: torch
    Found existing installation: torch 2.6.0.dev20240925+cu124
    Uninstalling torch-2.6.0.dev20240925+cu124:
      Successfully uninstalled torch-2.6.0.dev20240925+cu124
  WARNING: The scripts convert-caffe2-to-onnx.exe, convert-onnx-to-caffe2.exe, torchfrtrace.exe and torchrun.exe are installed in 'F:\Hybrid\64bit\Vapoursynth\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.20.0.dev20240926+cu124
    Uninstalling torchvision-0.20.0.dev20240926+cu124:
      Successfully uninstalled torchvision-0.20.0.dev20240926+cu124
Successfully installed torch-2.6.0.dev20241031+cu124 torchvision-0.20.0.dev20241031+cu124

F:\Hybrid\64bit\Vapoursynth>python -m pip install --pre -U torch torchvision --index-url https://download.pytorch.org/whl/nightly/cu124

F:\Hybrid\64bit\Vapoursynth>python -m pip install --no-deps --pre -U torch_tensorrt --index-url https://download.pytorch
.org/whl/nightly/cu124
Looking in indexes: https://download.pytorch.org/whl/nightly/cu124
Requirement already satisfied: torch_tensorrt in f:\hybrid\64bit\vapoursynth\lib\site-packages (2.6.0.dev20240926+cu124)
Collecting torch_tensorrt
  Downloading https://download.pytorch.org/whl/nightly/cu124/torch_tensorrt-2.6.0.dev20241031%2Bcu124-cp312-cp312-win_amd64.whl (2.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 5.3 MB/s eta 0:00:00
Installing collected packages: torch_tensorrt
  Attempting uninstall: torch_tensorrt
    Found existing installation: torch_tensorrt 2.6.0.dev20240926+cu124
    Uninstalling torch_tensorrt-2.6.0.dev20240926+cu124:
      Successfully uninstalled torch_tensorrt-2.6.0.dev20240926+cu124
Successfully installed torch_tensorrt-2.6.0.dev20241031+cu124

F:\Hybrid\64bit\Vapoursynth>python -m pip install -U tensorrt-cu12 tensorrt-cu12_bindings tensorrt-cu12_libs --extra-ind
ex-url https://pypi.nvidia.com
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Requirement already satisfied: tensorrt-cu12 in f:\hybrid\64bit\vapoursynth\lib\site-packages (10.3.0)
Collecting tensorrt-cu12
  Using cached tensorrt_cu12-10.5.0-py2.py3-none-any.whl
Requirement already satisfied: tensorrt-cu12_bindings in f:\hybrid\64bit\vapoursynth\lib\site-packages (10.3.0)
Collecting tensorrt-cu12_bindings
  Using cached https://pypi.nvidia.com/tensorrt-cu12-bindings/tensorrt_cu12_bindings-10.5.0-cp312-none-win_amd64.whl (772 kB)
Requirement already satisfied: tensorrt-cu12_libs in f:\hybrid\64bit\vapoursynth\lib\site-packages (10.3.0)
Collecting tensorrt-cu12_libs
  Downloading tensorrt_cu12_libs-10.6.0.tar.gz (626 bytes)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 116, in _iter_built_with_inserted
    candidate = func()
                ^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 187, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 233, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in __init__
    super().__init__(
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 159, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 236, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 315, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_internal\utils\misc.py", line 701, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nvidia_stub'
```

**Comment by HolyWu** [comment]
Looks like nvidia is going to release 10.6.0 soon but the wheel for Windows is not uploaded yet. You can specifically install 10.5.0 in the meantime by `pip install tensorrt-cu12==10.5.0 tensorrt-cu12_bindings==10.5.0 tensorrt-cu12_libs==10.5.0 --extra-index-url https://pypi.nvidia.com`.

**Comment by Selur** [comment]
Thanks! That seems to work. :)
